export type TrainingStatus = "APPROVED" | "AVAILABLE" | "LOCKED" | "PENDING";

export type AircraftCertification = {
  code: string;
  name: string;
  family: string;
  category: string;
  level: string;
  aliases: string[];
  minHours: number;
  costCoins: number;
  route: {
    origin: string;
    destination: string;
    alternate: string;
    cruiseLevel: string;
    distanceNm: number;
  };
  scenario: {
    title: string;
    objective: string;
    duration: string;
    weather: string;
    simulator: string;
  };
  criteria: string[];
  plan: string[];
};

export type RatingModule = {
  code: string;
  label: string;
  category: string;
  status: TrainingStatus;
  requiredFor: string;
  costCoins: number;
};

export type TheoryExam = {
  code: string;
  label: string;
  category: string;
  durationMinutes: number;
  passingScore: number;
  costCoins: number;
};

export const CHECKRIDE_FAILURE_POLICY = [
  "Cada solicitud de checkride registra un cobro virtual; el cargo se activara cuando se conecte economia/wallet.",
  "Si el piloto falla una vez, no podra repetir ese checkride durante 7 dias.",
  "Si falla dos veces consecutivas, el bloqueo sera de 15 dias.",
  "Si falla tres veces consecutivas, el bloqueo sera de 30 dias. Luego el contador vuelve a iniciar.",
  "El resultado oficial del checkride debe ser calculado y validado en servidor, no en el cliente.",
];

export const AIRCRAFT_CERTIFICATIONS: AircraftCertification[] = [
  {
    code: "C172",
    name: "Cessna 172 Skyhawk",
    family: "Escuela inicial",
    category: "Monomotor piston",
    level: "Inicial",
    aliases: ["C172", "C172_MSFS"],
    minHours: 0,
    costCoins: 50,
    route: { origin: "SCPF", destination: "SCTE", alternate: "SCJO", cruiseLevel: "VFR 045", distanceNm: 8 },
    scenario: {
      title: "Circuito visual y navegacion corta",
      objective: "Validar control basico, circuito de transito, aproximacion estabilizada y aterrizaje seguro.",
      duration: "35 a 50 min",
      weather: "VFR, viento menor a 15 kt y visibilidad superior a 8 km.",
      simulator: "MSFS 2020/2024 con avion C172 certificado o equivalente.",
    },
    criteria: [
      "Mantener velocidades de circuito y altitudes publicadas.",
      "Realizar taxi, despegue, tramo viento cruzado, base y final con procedimientos estables.",
      "Aterrizaje dentro de zona objetivo sin excursion de pista.",
      "Uso correcto de luces, transponder y comunicaciones simuladas.",
    ],
    plan: [
      "Salida desde SCPF o aerodromo escuela asignado.",
      "Circuito de transito completo y navegacion corta.",
      "Aproximacion visual estabilizada.",
      "Cierre con motor apagado y reporte de evaluacion.",
    ],
  },
  {
    code: "BE58",
    name: "Beechcraft Baron 58",
    family: "Multimotor piston",
    category: "Multimotor",
    level: "Basico multimotor",
    aliases: ["BE58", "BE58_MSFS", "BE58_BLACKSQUARE", "BE58_BS_PRO"],
    minHours: 5,
    costCoins: 90,
    route: { origin: "SCPF", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 090", distanceNm: 252 },
    scenario: {
      title: "Gestion multimotor y aproximacion IFR basica",
      objective: "Validar operacion multimotor, potencia, navegacion IFR basica y llegada estabilizada.",
      duration: "55 a 80 min",
      weather: "VFR/IFR ligero, techo superior a 2000 ft.",
      simulator: "BE58 MSFS o addon equivalente configurado sin asistencia irreal.",
    },
    criteria: [
      "Configuracion y chequeos antes de despegue completos.",
      "Gestion coordinada de potencia y mezcla durante ascenso/crucero.",
      "Aproximacion estabilizada y aterrizaje dentro de parametros.",
      "Sin excedencias criticas de velocidad, G o combustible.",
    ],
    plan: ["Salida IFR corta", "Navegacion directa o ruta corta", "Descenso planificado", "Aterrizaje y cierre en plataforma"],
  },
  {
    code: "C208",
    name: "Cessna Grand Caravan",
    family: "Turboprop regional",
    category: "Turboprop",
    level: "Monomotor turboprop",
    aliases: ["C208", "C208_MSFS", "C208_BLACKSQUARE"],
    minHours: 8,
    costCoins: 110,
    route: { origin: "SCPF", destination: "SCTE", alternate: "SCJO", cruiseLevel: "IFR 080", distanceNm: 8 },
    scenario: {
      title: "Operacion regional patagonica",
      objective: "Validar gestion turboprop, energia, performance y aproximacion corta.",
      duration: "40 a 65 min",
      weather: "Viento variable moderado, techo minimo 1800 ft.",
      simulator: "C208 MSFS o Black Square con perfil compatible.",
    },
    criteria: ["Control de torque/ITT", "Velocidad de aproximacion correcta", "Uso correcto de reversa si aplica", "Sin hard landing"],
    plan: ["Briefing de performance", "Salida corta", "Tramo regional", "Aproximacion visual/IFR y cierre"],
  },
  {
    code: "B350",
    name: "Beechcraft King Air 350",
    family: "Turboprop avanzado",
    category: "Turboprop",
    level: "Avanzado turboprop",
    aliases: ["B350", "B350_MSFS", "B350_BLACKSQUARE"],
    minHours: 12,
    costCoins: 140,
    route: { origin: "SCTE", destination: "SCIE", alternate: "SCEL", cruiseLevel: "IFR 180", distanceNm: 252 },
    scenario: { title: "Turboprop presurizado", objective: "Validar gestion de cabina, presurizacion simulada, aproximacion IFR y energia.", duration: "70 a 95 min", weather: "IFR ligero con viento moderado.", simulator: "King Air 350 certificado o equivalente." },
    criteria: ["Ascenso y crucero dentro de perfil", "Descenso con energia controlada", "Aproximacion estabilizada", "Taxi y cierre correcto"],
    plan: ["Briefing IFR", "Salida estandar", "Crucero y descenso", "Aproximacion y cierre"],
  },
  {
    code: "TBM9",
    name: "Daher TBM 930",
    family: "Turboprop ejecutivo",
    category: "Turboprop",
    level: "Ejecutivo",
    aliases: ["TBM9", "TBM9_MSFS", "TBM8_BLACKSQUARE"],
    minHours: 12,
    costCoins: 130,
    route: { origin: "SCTE", destination: "SCEL", alternate: "SCIE", cruiseLevel: "IFR 250", distanceNm: 495 },
    scenario: { title: "Operacion ejecutiva rapida", objective: "Validar planificacion, gestion de velocidad y descenso de alta performance.", duration: "90 a 120 min", weather: "Condiciones mixtas con alterno obligatorio.", simulator: "TBM 930/TBM 850 compatible." },
    criteria: ["Plan de descenso realista", "Gestion de velocidad", "Aproximacion estabilizada", "Combustible dentro de reserva"],
    plan: ["Despacho IFR", "Crucero alto", "Descenso gestionado", "Cierre ejecutivo"],
  },
  {
    code: "TBM8",
    name: "Daher TBM 850",
    family: "Turboprop ejecutivo",
    category: "Turboprop",
    level: "Ejecutivo",
    aliases: ["TBM8", "TBM8_BLACKSQUARE", "TBM9_MSFS"],
    minHours: 12,
    costCoins: 130,
    route: { origin: "SCTE", destination: "SCEL", alternate: "SCIE", cruiseLevel: "IFR 250", distanceNm: 495 },
    scenario: { title: "TBM manual avanzado", objective: "Validar gestion manual de potencia, energia y aproximacion estable.", duration: "90 a 120 min", weather: "Condiciones VMC/IMC ligeras.", simulator: "TBM 850 compatible." },
    criteria: ["Potencia dentro de limites", "Navegacion y descenso correctos", "Aterrizaje estable", "Cierre completo"],
    plan: ["Salida IFR", "Crucero alto", "Llegada controlada", "Reporte final"],
  },
  {
    code: "AT76",
    name: "ATR 72-600",
    family: "Regional turboprop",
    category: "Regional",
    level: "Regional",
    aliases: ["AT76", "ATR72", "ATR72_MSFS"],
    minHours: 20,
    costCoins: 180,
    route: { origin: "SCTE", destination: "SCIE", alternate: "SCEL", cruiseLevel: "IFR 190", distanceNm: 252 },
    scenario: { title: "Regional turboprop regular", objective: "Validar SOP regional, gestion de pasajeros y llegada regular.", duration: "70 a 100 min", weather: "METAR operativo y alterno disponible.", simulator: "ATR 72-600 compatible." },
    criteria: ["Checklist normal", "Energia en aproximacion", "Configuracion correcta", "Aterrizaje dentro de parametros"],
    plan: ["Embarque simulado", "Salida regular", "Crucero regional", "Llegada y cierre"],
  },
  {
    code: "ATR72",
    name: "ATR 72-600",
    family: "Regional turboprop",
    category: "Regional",
    level: "Regional",
    aliases: ["ATR72", "AT76", "ATR72_MSFS"],
    minHours: 20,
    costCoins: 180,
    route: { origin: "SCTE", destination: "SCIE", alternate: "SCEL", cruiseLevel: "IFR 190", distanceNm: 252 },
    scenario: { title: "Regional turboprop regular", objective: "Validar SOP regional, gestion de pasajeros y llegada regular.", duration: "70 a 100 min", weather: "METAR operativo y alterno disponible.", simulator: "ATR 72-600 compatible." },
    criteria: ["Checklist normal", "Energia en aproximacion", "Configuracion correcta", "Aterrizaje dentro de parametros"],
    plan: ["Embarque simulado", "Salida regular", "Crucero regional", "Llegada y cierre"],
  },
  {
    code: "E175",
    name: "Embraer 175",
    family: "Jet regional",
    category: "Regional jet",
    level: "Jet regional",
    aliases: ["E175", "E175_FLIGHTSIM"],
    minHours: 25,
    costCoins: 210,
    route: { origin: "SCIE", destination: "SCEL", alternate: "SCTE", cruiseLevel: "IFR 310", distanceNm: 232 },
    scenario: { title: "Jet regional inicial", objective: "Validar gestion FMS, velocidades, perfiles y aproximacion estabilizada.", duration: "60 a 90 min", weather: "IFR operativo.", simulator: "E175 compatible." },
    criteria: ["FMS cargado", "Perfil vertical razonable", "No excedencias", "Aterrizaje estable"],
    plan: ["Despacho jet", "SID/STAR", "Aproximacion ILS/RNAV", "Cierre"],
  },
  {
    code: "E190",
    name: "Embraer 190",
    family: "Jet regional",
    category: "Regional jet",
    level: "Jet regional",
    aliases: ["E190", "E190_FLIGHTSIM"],
    minHours: 28,
    costCoins: 230,
    route: { origin: "SCIE", destination: "SCEL", alternate: "SCTE", cruiseLevel: "IFR 330", distanceNm: 232 },
    scenario: { title: "Jet regional medio", objective: "Validar control de energia y operacion regional a mayor capacidad.", duration: "60 a 90 min", weather: "IFR operativo.", simulator: "E190 compatible." },
    criteria: ["Velocidades correctas", "Descenso controlado", "Aproximacion estable", "Cierre correcto"],
    plan: ["Salida regular", "Crucero regional", "Llegada STAR", "Reporte final"],
  },
  {
    code: "E195",
    name: "Embraer 195",
    family: "Jet regional",
    category: "Regional jet",
    level: "Jet regional avanzado",
    aliases: ["E195", "E195_FLIGHTSIM"],
    minHours: 30,
    costCoins: 240,
    route: { origin: "SCIE", destination: "SCEL", alternate: "SCTE", cruiseLevel: "IFR 330", distanceNm: 232 },
    scenario: { title: "Jet regional avanzado", objective: "Validar SOP y energia con mayor peso operacional.", duration: "60 a 95 min", weather: "IFR operativo.", simulator: "E195 compatible." },
    criteria: ["MCDU/FMS correcto", "Gestion de peso", "Aproximacion estabilizada", "Sin eventos criticos"],
    plan: ["Briefing", "Salida", "Crucero", "Llegada y cierre"],
  },
  {
    code: "A319",
    name: "Airbus A319",
    family: "Airbus narrowbody",
    category: "Jet comercial",
    level: "Narrowbody",
    aliases: ["A319", "A319_FENIX", "A319_LATINVFR"],
    minHours: 40,
    costCoins: 320,
    route: { origin: "SCEL", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 330", distanceNm: 232 },
    scenario: { title: "Airbus narrowbody inicial", objective: "Validar automatizacion Airbus, managed modes y aproximacion estabilizada.", duration: "65 a 95 min", weather: "IFR normal.", simulator: "A319 certificado o familia Airbus compatible." },
    criteria: ["FCU/MCDU coherente", "Managed/selected modes correctos", "Configuracion estabilizada", "Autobrake/reversas dentro de SOP"],
    plan: ["Despacho Airbus", "SID", "Cruce y descenso", "ILS/RNAV y cierre"],
  },
  {
    code: "A320",
    name: "Airbus A320",
    family: "Airbus narrowbody",
    category: "Jet comercial",
    level: "Narrowbody",
    aliases: ["A320", "A320_FENIX", "A320_LATINVFR"],
    minHours: 45,
    costCoins: 350,
    route: { origin: "SCEL", destination: "SCTE", alternate: "SCIE", cruiseLevel: "IFR 350", distanceNm: 495 },
    scenario: { title: "Airbus A320 ruta troncal", objective: "Validar operacion comercial completa, planificacion, automatizacion y combustible.", duration: "95 a 130 min", weather: "IFR con alterno obligatorio.", simulator: "A320 Fenix/LatinVFR/MSFS compatible." },
    criteria: ["OFP coherente", "MCDU y performance configurados", "STAR/approach correctas", "Cierre sin penalizaciones criticas"],
    plan: ["Salida troncal", "Crucero FL350", "Llegada Patagonia", "Cierre postvuelo"],
  },
  {
    code: "A20N",
    name: "Airbus A320neo",
    family: "Airbus narrowbody",
    category: "Jet comercial",
    level: "Narrowbody NEO",
    aliases: ["A20N", "A20N_FBW"],
    minHours: 45,
    costCoins: 360,
    route: { origin: "SCEL", destination: "SCTE", alternate: "SCIE", cruiseLevel: "IFR 350", distanceNm: 495 },
    scenario: { title: "Airbus A320neo eficiencia operacional", objective: "Validar gestion moderna del A320neo y combustible planificado.", duration: "95 a 130 min", weather: "IFR con alterno obligatorio.", simulator: "A20N FBW o equivalente." },
    criteria: ["Performance coherente", "Perfil vertical", "Fuel final suficiente", "Aterrizaje estable"],
    plan: ["Despacho NEO", "SID/STAR", "Optimizar consumo", "Cierre"],
  },
  {
    code: "A321",
    name: "Airbus A321",
    family: "Airbus narrowbody",
    category: "Jet comercial",
    level: "Narrowbody pesado",
    aliases: ["A321", "A321_FENIX"],
    minHours: 55,
    costCoins: 390,
    route: { origin: "SCEL", destination: "SCFA", alternate: "SCDA", cruiseLevel: "IFR 350", distanceNm: 598 },
    scenario: { title: "A321 gestion de peso", objective: "Validar operacion narrowbody pesado y energia de aproximacion.", duration: "100 a 140 min", weather: "IFR normal.", simulator: "A321 compatible." },
    criteria: ["Peso y velocidades correctos", "Descenso anticipado", "Aproximacion estable", "Sin tailstrike"],
    plan: ["Salida norte", "Crucero", "Llegada desertica", "Cierre"],
  },
  {
    code: "A21N",
    name: "Airbus A321neo",
    family: "Airbus narrowbody",
    category: "Jet comercial",
    level: "Narrowbody pesado NEO",
    aliases: ["A21N", "A21N_LATINVFR"],
    minHours: 55,
    costCoins: 400,
    route: { origin: "SCEL", destination: "SCFA", alternate: "SCDA", cruiseLevel: "IFR 350", distanceNm: 598 },
    scenario: { title: "A321neo operacion extendida", objective: "Validar eficiencia, energia y gestion de mayor alcance.", duration: "100 a 145 min", weather: "IFR normal.", simulator: "A21N compatible." },
    criteria: ["Fuel plan realista", "Velocidades correctas", "Aproximacion estable", "Cierre SOP"],
    plan: ["Despacho", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "A339",
    name: "Airbus A330-900neo",
    family: "Widebody Airbus",
    category: "Widebody",
    level: "Largo alcance",
    aliases: ["A339", "A339_HEADWIND"],
    minHours: 100,
    costCoins: 650,
    route: { origin: "SCEL", destination: "SBGR", alternate: "SAEZ", cruiseLevel: "IFR 390", distanceNm: 1410 },
    scenario: { title: "Widebody Airbus internacional", objective: "Validar largo alcance, combustible, peso y aproximacion pesada.", duration: "180 a 230 min", weather: "Internacional IFR con alterno.", simulator: "A339 Headwind o equivalente." },
    criteria: ["OFP internacional", "Fuel y alterno", "Gestion heavy", "Aterrizaje estable"],
    plan: ["Salida internacional", "Crucero", "Llegada internacional", "Cierre"],
  },
  {
    code: "A359",
    name: "Airbus A350-900",
    family: "Widebody Airbus",
    category: "Widebody",
    level: "Largo alcance",
    aliases: ["A359", "A359_INIBUILDS"],
    minHours: 110,
    costCoins: 700,
    route: { origin: "SCEL", destination: "KMIA", alternate: "KATL", cruiseLevel: "IFR 390", distanceNm: 3580 },
    scenario: { title: "Widebody transcontinental", objective: "Validar operacion long range y gestion avanzada.", duration: "300+ min", weather: "Largo alcance con alterno obligatorio.", simulator: "A359 compatible." },
    criteria: ["Plan long range", "Fuel final", "Descenso y STAR", "Aterrizaje pesado"],
    plan: ["Despacho oceanico", "Crucero largo", "Llegada internacional", "Cierre"],
  },
  {
    code: "B736",
    name: "Boeing 737-600",
    family: "Boeing 737 NG",
    category: "Jet comercial",
    level: "Narrowbody",
    aliases: ["B736", "B736_PMDG"],
    minHours: 40,
    costCoins: 330,
    route: { origin: "SCEL", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 330", distanceNm: 232 },
    scenario: { title: "Boeing 737 inicial", objective: "Validar MCP, LNAV/VNAV y perfiles Boeing.", duration: "65 a 95 min", weather: "IFR normal.", simulator: "B736 PMDG o equivalente." },
    criteria: ["MCP correcto", "VNAV/LNAV razonable", "Approach estable", "Cierre SOP"],
    plan: ["Salida", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "B737",
    name: "Boeing 737-700",
    family: "Boeing 737 NG",
    category: "Jet comercial",
    level: "Narrowbody",
    aliases: ["B737", "B737_PMDG"],
    minHours: 45,
    costCoins: 350,
    route: { origin: "SCEL", destination: "SCTE", alternate: "SCIE", cruiseLevel: "IFR 350", distanceNm: 495 },
    scenario: { title: "Boeing 737 ruta troncal", objective: "Validar operacion comercial Boeing y energia de aproximacion.", duration: "95 a 130 min", weather: "IFR con alterno.", simulator: "B737 PMDG o equivalente." },
    criteria: ["FMC correcto", "VNAV/LNAV", "Estabilizado a 1000 ft", "Cierre normal"],
    plan: ["Salida SCEL", "Crucero", "Llegada SCTE", "Postvuelo"],
  },
  {
    code: "B738",
    name: "Boeing 737-800",
    family: "Boeing 737 NG",
    category: "Jet comercial",
    level: "Narrowbody",
    aliases: ["B738", "B738_PMDG"],
    minHours: 45,
    costCoins: 360,
    route: { origin: "SCEL", destination: "SCTE", alternate: "SCIE", cruiseLevel: "IFR 350", distanceNm: 495 },
    scenario: { title: "Boeing 737-800 comercial", objective: "Validar performance, automatizacion y landing SOP.", duration: "95 a 130 min", weather: "IFR con alterno.", simulator: "B738 PMDG o equivalente." },
    criteria: ["FMC/performance", "Config flaps correcta", "Aproximacion estable", "Sin excedencias"],
    plan: ["Despacho", "Salida", "Crucero", "Llegada"],
  },
  {
    code: "B739",
    name: "Boeing 737-900",
    family: "Boeing 737 NG",
    category: "Jet comercial",
    level: "Narrowbody pesado",
    aliases: ["B739", "B739_PMDG"],
    minHours: 55,
    costCoins: 390,
    route: { origin: "SCEL", destination: "SCFA", alternate: "SCDA", cruiseLevel: "IFR 350", distanceNm: 598 },
    scenario: { title: "Boeing 737-900 peso y pista", objective: "Validar gestion de mayor longitud y performance.", duration: "100 a 140 min", weather: "IFR normal.", simulator: "B739 PMDG o equivalente." },
    criteria: ["Performance de pista", "Energia de aproximacion", "Aterrizaje estable", "Cierre"],
    plan: ["Salida", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "B38M",
    name: "Boeing 737 MAX 8",
    family: "Boeing 737 MAX",
    category: "Jet comercial",
    level: "Narrowbody MAX",
    aliases: ["B38M", "B38M_IFLY"],
    minHours: 60,
    costCoins: 420,
    route: { origin: "SCEL", destination: "SCFA", alternate: "SCDA", cruiseLevel: "IFR 370", distanceNm: 598 },
    scenario: { title: "737 MAX operacion moderna", objective: "Validar eficiencia, automatizacion y perfiles MAX.", duration: "100 a 145 min", weather: "IFR normal.", simulator: "B38M iFly o equivalente." },
    criteria: ["FMC correcto", "Perfil eficiente", "Approach estable", "Fuel final"],
    plan: ["Despacho MAX", "Salida", "Crucero", "Llegada"],
  },
  {
    code: "B772",
    name: "Boeing 777-200",
    family: "Boeing widebody",
    category: "Widebody",
    level: "Largo alcance",
    aliases: ["B772", "B772_PMDG"],
    minHours: 110,
    costCoins: 720,
    route: { origin: "SCEL", destination: "KMIA", alternate: "KATL", cruiseLevel: "IFR 390", distanceNm: 3580 },
    scenario: { title: "Boeing 777 largo alcance", objective: "Validar plan long range, heavy operations y combustible.", duration: "300+ min", weather: "Internacional con alterno.", simulator: "B772 PMDG o equivalente." },
    criteria: ["Fuel long range", "FMC heavy", "Descenso anticipado", "Aterrizaje pesado"],
    plan: ["Salida internacional", "Crucero oceanico", "STAR", "Cierre"],
  },
  {
    code: "B77W",
    name: "Boeing 777-300ER",
    family: "Boeing widebody",
    category: "Widebody",
    level: "Largo alcance pesado",
    aliases: ["B77W", "B77W_PMDG"],
    minHours: 120,
    costCoins: 760,
    route: { origin: "SCEL", destination: "KMIA", alternate: "KATL", cruiseLevel: "IFR 390", distanceNm: 3580 },
    scenario: { title: "B777-300ER heavy", objective: "Validar peso, energia y llegada heavy.", duration: "300+ min", weather: "Internacional con alterno.", simulator: "B77W PMDG o equivalente." },
    criteria: ["Peso y combustible", "Descenso anticipado", "Approach heavy", "Cierre sin excedencias"],
    plan: ["Despacho heavy", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "B789",
    name: "Boeing 787-9 Dreamliner",
    family: "Boeing widebody",
    category: "Widebody",
    level: "Largo alcance moderno",
    aliases: ["B789", "B789_HORIZONS"],
    minHours: 105,
    costCoins: 700,
    route: { origin: "SCEL", destination: "KJFK", alternate: "KBOS", cruiseLevel: "IFR 410", distanceNm: 4450 },
    scenario: { title: "B787-9 long range", objective: "Validar gestion moderna, largo alcance y aproximacion internacional.", duration: "300+ min", weather: "Internacional long range.", simulator: "B789 Horizons o equivalente." },
    criteria: ["OFP long range", "Fuel final", "VNAV", "Cierre"],
    plan: ["Salida", "Crucero long range", "Llegada", "Cierre"],
  },
  {
    code: "B78X",
    name: "Boeing 787-10 Dreamliner",
    family: "Boeing widebody",
    category: "Widebody",
    level: "Widebody moderno",
    aliases: ["B78X", "B78X_MSFS"],
    minHours: 105,
    costCoins: 690,
    route: { origin: "SCEL", destination: "SBGR", alternate: "SAEZ", cruiseLevel: "IFR 390", distanceNm: 1410 },
    scenario: { title: "B787-10 regional largo", objective: "Validar heavy moderno y rutas sudamericanas.", duration: "180 a 230 min", weather: "IFR internacional.", simulator: "B78X MSFS o equivalente." },
    criteria: ["VNAV/FMS", "Peso", "Aproximacion heavy", "Fuel final"],
    plan: ["Despacho", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "MD82",
    name: "McDonnell Douglas MD-82",
    family: "Maddog",
    category: "Jet clasico",
    level: "Jet clasico",
    aliases: ["MD82", "MD82_MADDOG"],
    minHours: 70,
    costCoins: 430,
    route: { origin: "SCEL", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 310", distanceNm: 232 },
    scenario: { title: "Jet clasico manual", objective: "Validar gestion clasica, potencia y aproximacion manual.", duration: "70 a 100 min", weather: "IFR normal.", simulator: "Maddog MD-82 o equivalente." },
    criteria: ["Checklist clasico", "Gestion manual", "Approach estable", "Cierre"],
    plan: ["Salida", "Crucero", "Aproximacion", "Cierre"],
  },
  {
    code: "MD83",
    name: "McDonnell Douglas MD-83",
    family: "Maddog",
    category: "Jet clasico",
    level: "Jet clasico",
    aliases: ["MD83", "MD83_MADDOG"],
    minHours: 70,
    costCoins: 440,
    route: { origin: "SCEL", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 310", distanceNm: 232 },
    scenario: { title: "MD-83 gestion clasica", objective: "Validar perfiles, potencia y energy management.", duration: "70 a 100 min", weather: "IFR normal.", simulator: "Maddog MD-83 o equivalente." },
    criteria: ["Checklist", "Potencia", "Approach", "Cierre"],
    plan: ["Salida", "Crucero", "Llegada", "Cierre"],
  },
  {
    code: "MD88",
    name: "McDonnell Douglas MD-88",
    family: "Maddog",
    category: "Jet clasico",
    level: "Jet clasico avanzado",
    aliases: ["MD88", "MD88_MADDOG"],
    minHours: 75,
    costCoins: 450,
    route: { origin: "SCEL", destination: "SCIE", alternate: "SCTE", cruiseLevel: "IFR 310", distanceNm: 232 },
    scenario: { title: "MD-88 checkride avanzado", objective: "Validar operacion clasica avanzada y aproximacion manual.", duration: "70 a 105 min", weather: "IFR normal.", simulator: "Maddog MD-88 o equivalente." },
    criteria: ["Control manual", "Checklist", "Energia", "Cierre"],
    plan: ["Briefing", "Salida", "Llegada", "Reporte final"],
  },
];

export const RATING_MODULES: RatingModule[] = [
  { code: "INSTRUMENTAL_I", label: "Instrumental I", category: "IFR", status: "AVAILABLE", requiredFor: "Rutas oficiales escuela y aproximaciones IFR basicas", costCoins: 120 },
  { code: "INSTRUMENTAL_II", label: "Instrumental II", category: "IFR", status: "PENDING", requiredFor: "Rutas IFR regulares y STAR/SID complejas", costCoins: 180 },
  { code: "INSTRUMENTAL_CAT_I", label: "Instrumental CAT I", category: "IFR", status: "PENDING", requiredFor: "Operaciones ILS CAT I", costCoins: 220 },
  { code: "INSTRUMENTAL_CAT_II", label: "Instrumental CAT II", category: "IFR", status: "PENDING", requiredFor: "Baja visibilidad avanzada", costCoins: 320 },
  { code: "CROSSWIND_20", label: "Viento cruzado 20KT", category: "Meteo", status: "AVAILABLE", requiredFor: "Aeropuertos patagonicos con viento moderado", costCoins: 150 },
  { code: "CROSSWIND_30", label: "Viento cruzado 30KT", category: "Meteo", status: "PENDING", requiredFor: "Operacion avanzada con viento fuerte", costCoins: 250 },
  { code: "TURBOPROP", label: "Turboprop", category: "Aeronave", status: "AVAILABLE", requiredFor: "C208, B350, TBM y ATR", costCoins: 160 },
  { code: "JET_NARROWBODY", label: "Jet Narrowbody", category: "Aeronave", status: "PENDING", requiredFor: "A320/B737/E-Jets comerciales", costCoins: 300 },
  { code: "WIDEBODY", label: "Widebody", category: "Aeronave", status: "PENDING", requiredFor: "A330/A350/B777/B787", costCoins: 500 },
  { code: "INTERNATIONAL", label: "Operacion internacional", category: "Ruta", status: "PENDING", requiredFor: "Cruce de fronteras y rutas internacionales", costCoins: 280 },
  { code: "OCEANIC", label: "Operacion oceanica", category: "Ruta", status: "PENDING", requiredFor: "Isla de Pascua y vuelos oceanicos", costCoins: 420 },
  { code: "PATAGONIA_SOUTH", label: "Patagonia Sur", category: "Ruta", status: "AVAILABLE", requiredFor: "SCCI, SCBA y aerodromos australes", costCoins: 180 },
];

export const THEORY_EXAMS: TheoryExam[] = [
  { code: "PWG_REGS", label: "Normativa Patagonia Wings", category: "Base", durationMinutes: 30, passingScore: 80, costCoins: 40 },
  { code: "BASIC_MET", label: "Meteorologia operacional", category: "Meteo", durationMinutes: 40, passingScore: 80, costCoins: 60 },
  { code: "BASIC_NAV", label: "Navegacion y plan de vuelo", category: "Operacion", durationMinutes: 40, passingScore: 80, costCoins: 60 },
  { code: "RADIO_COMMS", label: "Comunicaciones y fraseologia", category: "ATC", durationMinutes: 30, passingScore: 80, costCoins: 50 },
  { code: "SIMBRIEF_OFP", label: "SimBrief / OFP operacional", category: "Despacho", durationMinutes: 35, passingScore: 80, costCoins: 55 },
  { code: "JET_PERF", label: "Performance jet", category: "Performance", durationMinutes: 45, passingScore: 85, costCoins: 90 },
  { code: "IFR_PROC", label: "Procedimientos IFR", category: "IFR", durationMinutes: 45, passingScore: 85, costCoins: 90 },
  { code: "PWG_SOP", label: "SOP Patagonia Wings", category: "Compania", durationMinutes: 35, passingScore: 85, costCoins: 70 },
];

export function getCertificationByCode(code: string) {
  const normalized = code.trim().toUpperCase();
  return AIRCRAFT_CERTIFICATIONS.find((item) => item.code === normalized || item.aliases.includes(normalized)) ?? null;
}

export function isAircraftCertified(permitted: string[] | null | undefined, cert: AircraftCertification) {
  const set = new Set((permitted ?? []).map((item) => item.trim().toUpperCase()).filter(Boolean));
  return cert.aliases.some((alias) => set.has(alias)) || set.has(cert.code);
}
